sudo: required
services:
  - docker

before_install:
  - docker build -t client-image -f ./client/Dockerfile.dev ./client

script:
  - docker run client-image npm run test -- --coverage

after_success:
  - docker build -t kylecooley/fib-nginx ./nginx
  - docker build -t kylecooley/fib-client ./client
  - docker build -t kylecooley/fib-server ./server
  - docker build -t kylecooley/fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kylecooley/fib-nginx
  - docker push kylecooley/fib-client
  - docker push kylecooley/fib-server
  - docker push kylecooley/fib-worker
