version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - client
      - api
    restart: "always"
    ports:
      - "8080:80"
  redis:
    image: "redis"
  postgres:
    image: "postgres"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
      - postgres
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "PGHOST=postgres"
      - "PGPORT=5432"
      - "PGDATABASE=postgres"
      - "PGUSER=postgres"
      - "PGPASSWORD=postgres_password"
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    depends_on:
      - redis
    volumes:
      - /app/node_modules
      - ./worker:/app
